module sr_latch_tb();

reg s,r;
wire q,qbar;

sr_latch dut(s,r,q,qbar);

initial
begin
    s=0; r=0;
    #10 s=1; r=0;
    #10 s=0; r=0;
    #10 s=0; r=1;
    #10 s=0; r=0;
    #10 s=1; r=1;
    #10 $finish;
end

initial
$monitor("s=%b r=%b q=%b qbar=%b",s,r,q,qbar);

endmodule
