module comparator_1bit_tb;

reg A, B;
wire GT, LT, EQ;

comparator_1bit dut(
    .A(A),
    .B(B),
    .GT(GT),
    .LT(LT),
    .EQ(EQ)
);

initial begin

    $monitor("A=%b B=%b GT=%b LT=%b EQ=%b",
              A,B,GT,LT,EQ);

    A=0; B=0;
    #10 A=0; B=1;
    #10 A=1; B=0;
    #10 A=1; B=1;

end

endmodule